spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lic_vetlink
    password: vetlink
    username: vetlink
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: romeo.vasil2001@gmail.com
    password: pjbo hhmi azps grsk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
